[package]
name = "dk"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
dkb-core = { path = "../dkb-core" }
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lib]
name = "dk"
path = "src/lib.rs"

[[bin]]
name = "dk"
path = "src/main.rs"
